name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      # ---------- USER SERVICE ----------
      - name: Build User Service image
        working-directory: python-task/microservices-project/user-service
        run: docker build -t ${{ secrets.DOCKER_USER }}/user-service:latest .

      - name: Push User Service image
        run: docker push ${{ secrets.DOCKER_USER }}/user-service:latest

      # ---------- TASK SERVICE ----------
      - name: Build Task Service image
        working-directory: python-task/microservices-project/task-service
        run: docker build -t ${{ secrets.DOCKER_USER }}/task-service:latest .

      - name: Push Task Service image
        run: docker push ${{ secrets.DOCKER_USER }}/task-service:latest

      # ---------- GATEWAY SERVICE ----------
      - name: Build Gateway Service image
        working-directory: python-task/microservices-project/gateway-service
        run: docker build -t ${{ secrets.DOCKER_USER }}/gateway-service:latest .

      - name: Push Gateway Service image
        run: docker push ${{ secrets.DOCKER_USER }}/gateway-service:latest
