name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        working-directory: pipeline-practice
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-flask-app:latest .

      - name: "Stage 4: Tag Docker Image with Commit SHA"
        working-directory: pipeline-practice
        run: |
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          docker tag ${{ secrets.DOCKER_USERNAME }}/devops-flask-app:latest ${{ secrets.DOCKER_USERNAME }}/ris-devops-practice-project:$COMMIT_SHA

      - name: Testing the Docker image with Trivy
        uses : aquasecurity/trivy-action@master
        with : 
          image-ref : ${{ secrets.DOCKER_USERNAME }}/devops-flask-app:latest
          format: table
          exit-code: 0
          ignore-unfixed: true

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-flask-app:latest
           COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          docker push ${{ secrets.DOCKER_USERNAME }}/ris-devops-practice-project:$COMMIT_SHA

