
services:
  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newpassword
      POSTGRES_DB: user_service_db
    volumes:
      - user_data:/var/lib/postgresql/data
    networks:
      - micro-net

  task-db:
    image: postgres:15
    container_name: task-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newpassword
      POSTGRES_DB: task_service_db
    volumes:
      - task_data:/var/lib/postgresql/data
    networks:
      - micro-net

  user-service:
    build: ./user-service
    container_name: user-service
    depends_on:
      - user-db
    environment:
      DB_URL: postgresql+asyncpg://postgres:newpassword@user-db:5432/user_service_db
    ports:
      - "8000:8000"
    networks:
      - micro-net

  task-service:
    build: ./task-service
    container_name: task-service
    depends_on:
      - task-db
    environment:
      DB_URL: postgresql+asyncpg://postgres:newpassword@task-db:5432/task_service_db
    ports:
      - "8001:8001"
    networks:
      - micro-net

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    depends_on:
      - user-service
      - task-service
    ports:
      - "8002:8000"
    networks:
      - micro-net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - gateway-service
    networks:
      - micro-net

networks:
  micro-net:

volumes:
  user_data:
  task_data:
